# Generated by Django 4.0.3 on 2022-03-21 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.IntegerField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('courseDescription', models.TextField()),
                ('active', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('studentCourseId', models.IntegerField(primary_key=True, serialize=False)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name_plural': 'StudentCourse',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialTitle', models.CharField(max_length=50, null=True)),
                ('materialDescription', models.TextField(null=True)),
                ('active', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('materialURL', models.URLField(null=True)),
                ('batchId', models.ManyToManyField(to='batch.batch')),
                ('courseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name_plural': 'Material',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceId', models.IntegerField(primary_key=True, serialize=False)),
                ('batchId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batch.batch')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
            },
        ),
    ]
