# Generated by Django 4.0.3 on 2022-03-21 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchId', models.IntegerField(primary_key=True, serialize=False)),
                ('batchName', models.CharField(max_length=50)),
                ('batchdescription', models.CharField(max_length=50)),
                ('batchStartDate', models.DateField()),
                ('batchEndDate', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Batch',
            },
        ),
        migrations.CreateModel(
            name='BatchTime',
            fields=[
                ('batchTimeId', models.IntegerField(primary_key=True, serialize=False)),
                ('batchDay', models.DateField()),
                ('BatchTime', models.TimeField()),
                ('BatchDuration', models.DurationField()),
                ('batchId', models.ManyToManyField(to='batch.batch')),
            ],
            options={
                'verbose_name_plural': 'BatchTime',
            },
        ),
        migrations.CreateModel(
            name='BatchDetail',
            fields=[
                ('batch_detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('batchId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batch.batch')),
            ],
            options={
                'verbose_name_plural': 'BatchDetails',
            },
        ),
    ]
